import com.leapmotion.leap.*;
import java.applet.*;
import java.awt.*;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Rectangle2D;
import javax.swing.*;

public class MainApplet extends Applet implements ActionListener{
    private SynthListener listener;
    private Controller controller;

//    private Point2D.Double leftHand, rightHand;
    private double leftX, leftY, rightX, rightY;

    private boolean onScreen, closedHand;

    private int circleDiameter;

    private int instrumentNum;

    private long lastSwipeTimeMillis;

    

    private MediaTracker mt;
    private Image[] instrumentImages;
    private Image leftArrow, rightArrow;

     public void init(){
         setSize(1080, 840);

        instrumentImages = new Image[5];

         mt = new MediaTracker(this);

         // The try-catch is necassary when the URL isn't valid
         // Ofcourse this one is valid, since it is generated by
         // Java itself.
        java.net.URL base = getDocumentBase();


         // Here we load the image.
         // Only Gif and JPG are allowed. Transparant gif also.

         instrumentImages[0] = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/bass.png");
         instrumentImages[1] = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/keyboard.png");
         instrumentImages[2] = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/strings.png");
         instrumentImages[3] = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/horns.png");
         instrumentImages[4] = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/cow.png");
         leftArrow = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/leftArrow.png");
         rightArrow = Toolkit.getDefaultToolkit().getImage("/Users/Matt/Programming/Personal Projects/synthCOW-v2.0/synthCOW-project/src/images/rightArrow.png");

         // tell the MediaTracker to kep an eye on this image, and give it ID 1;
         for (int i = 0; i < instrumentImages.length; i++) {
             mt.addImage(instrumentImages[i], i);
             System.out.println(instrumentImages[i].getWidth(null) + " " + instrumentImages[i].getHeight(null));
         }
         mt.addImage(leftArrow, 98);
         mt.addImage(rightArrow, 99);

         // now tell the mediaTracker to stop the applet execution
         // (in this example don't paint) until the images are fully loaded.
         // must be in a try catch block.

         try {
             mt.waitForAll();
         }
         catch (InterruptedException  e) {}

//         leftHand = new Point2D.Double(10, 10);
//         rightHand = new Point2D.Double(200, 200);

         leftX = 10; leftY = 10;
         rightX = 200; rightY = 200;

         circleDiameter = 100;

         instrumentNum = 0;

         lastSwipeTimeMillis = 0;

         //setup leapmotion
         // Create a sample listener and controller
         listener = new SynthListener();
         controller = new Controller();

         // Have the sample listener receive events from the controller
         controller.addListener(listener);

         Timer t = new Timer(100, this);
         t.start();
     }

    public void actionPerformed(ActionEvent e) {
        com.leapmotion.leap.Frame frame = controller.frame();

        if(frame.hands().count() == 2){
            onScreen = true;

            double rx = frame.hands().rightmost().fingers().frontmost().tipPosition().getX();
            double ry = frame.hands().rightmost().fingers().frontmost().tipPosition().getY();
            double lx = frame.hands().leftmost().fingers().frontmost().tipPosition().getX();
            double ly = frame.hands().leftmost().fingers().frontmost().tipPosition().getY();

            double xPos = 2*rx + 500 + 40;//x from leap goes -250 to 250, plus 20px buffer on side @2x
            if (xPos < 40){
                xPos = 40;
            }else if (xPos > 1040-circleDiameter){
                xPos = 1040-circleDiameter;
            }

            double yPos = 200 + (600 - 2*ry + 60);//invert y coords from leap and give 100px margin at top @2x
            if (yPos > 800-circleDiameter){
                yPos = 800-circleDiameter;
            }else if (yPos < 200){
                yPos = 200;
            }

            rightX = xPos;
            rightY = yPos;

            xPos = 2*lx + 500 + 40;//x from leap goes -250 to 250, plus 20px buffer on side @2x
            if (xPos < 40){
                xPos = 40;
            }else if (xPos > 1040-circleDiameter){
                xPos = 1040-circleDiameter;
            }

            yPos = 200 + (600 - 2*ly + 60);//invert y coords from leap and give 100px margin at top @2x
            if (yPos > 800-circleDiameter){
                yPos = 800-circleDiameter;
            }else if (yPos < 200) {
                yPos = 200;
            }

            leftX = xPos;
            leftY = yPos;

            closedHand = frame.hands().rightmost().grabStrength() > .6;
        }
        else{
            onScreen = false;
        }

        repaint();
    }
    public void paint(Graphics g){
        Graphics2D g2 = (Graphics2D)g;

        //
        //draw background
        //
        double pitch = (1000-leftY)/600;
        double volume = (1000-rightY)*0.5/600;

        Color bgColor = Color.getHSBColor((float)pitch, 1f, (float)volume);
        setBackground(bgColor);

        //draw instrument image/handle swipes
        long curTime = System.currentTimeMillis();
        int change = listener.getSwipeNum();
        System.out.println("curTime: "+curTime+", lastSwipeTime: "+lastSwipeTimeMillis);
        if (curTime - lastSwipeTimeMillis >= 1500){
            if (change == -1){
                listener.getGh().changeInstrument(false);
                lastSwipeTimeMillis = curTime;
            }else if (change == 1){
                listener.getGh().changeInstrument(true);
                lastSwipeTimeMillis = curTime;
            }

            instrumentNum += change;

            if (instrumentNum > 4){
                instrumentNum = 0;
            }else if (instrumentNum < 0){
                instrumentNum = 4;
            }


        }

//        System.out.println(instrumentImages[0].getWidth(null) + " " + instrumentImages[0].getHeight(null));
        g2.drawImage(instrumentImages[instrumentNum], 500, 60, 80, 80, this);
        g2.drawImage(leftArrow, 434, 80, 36, 40, this);
        g2.drawImage(rightArrow, 610, 80, 36, 40, this);

        g2.setColor(Color.white);
//        g2.drawString(""+instrumentNum, 10, 20);

        //note lines

        Rectangle2D line1 = new Rectangle2D.Double(40, 200, 1000, 120);
        Rectangle2D line3 = new Rectangle2D.Double(40, 440, 1000, 120);
        Rectangle2D line5 = new Rectangle2D.Double(40, 680, 1000, 120);

        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);

        float[] fractions = {0f, 0.8f};
        Color[] colors = {new Color(1f, 1f, 1f, 0.4f), new Color(1f, 1f, 1f, 0f)};
        LinearGradientPaint paint = new LinearGradientPaint(40, 0, 1000, 0, fractions, colors);
        g2.setPaint(paint);

        g2.fill(line1);
        g2.fill(line3);
        g2.fill(line5);

        //brackets
        g2.setColor(Color.white);
        g2.setStroke(new BasicStroke(1));

        g2.drawLine(40, 200, 40, 800);
        g2.drawLine(40, 200, 48, 200);
        g2.drawLine(40, 800, 48, 800);

        g2.drawLine(1040, 200, 1040, 800);
        g2.drawLine(1032, 200, 1040, 200);
        g2.drawLine(1032, 800, 1040, 800);

//        System.out.println("REPAINT L: (" + leftX + ", " + leftY + ")");
//        System.out.println("REPAINT R: ("+rightX+", "+rightY+")");

        //draw hand-circles
        if(onScreen) {
            g2.setStroke(new BasicStroke(3));

            g2.drawOval((int) leftX, (int) leftY, circleDiameter, circleDiameter);

            if (closedHand){
                g2.setColor(new Color(1f, 1f, 1f, 0.4f));
            }
            g2.drawOval((int) rightX, (int) rightY, circleDiameter, circleDiameter);

            g2.setColor(new Color(1f, 1f, 1f, 0.5f));

            g2.fillOval((int) leftX, (int) leftY, circleDiameter, circleDiameter);

            if (closedHand){
                g2.setColor(new Color(1f, 1f, 1f, 0.2f));
            }
            g2.fillOval((int) rightX, (int) rightY, circleDiameter, circleDiameter);
        }
    }

    private java.awt.Image dbImage;
    private Graphics dbg;
    public void update (Graphics g){
        if (dbImage == null) {
            dbImage = createImage (this.getSize().width, this.getSize().height);
            dbg = dbImage.getGraphics ();
        }
        dbg.setColor (getBackground ());
        dbg.fillRect (0, 0, this.getSize().width, this.getSize().height);
        dbg.setColor (getForeground());
        paint (dbg);
        g.drawImage (dbImage, 0, 0, this);
    }
}